package roles_test

import (
	"strings"
	"testing"

	"github.com/git-pkgs/roles"
)

const clientGo = "client.go"

func TestBlob(t *testing.T) {
	for _, tc := range []struct {
		name, path, text   string
		generated, limited bool
	}{
		{"go marker", "src/client.go", "// Code generated by clientgen. DO NOT EDIT.\npackage client\n", true, false},
		{"crlf", clientGo, "// Code generated by clientgen. DO NOT EDIT.\r\npackage client\r\n", true, false},
		{"quoted", "client_test.go", "package client\nvar marker = \"// Code generated by clientgen. DO NOT EDIT.\"\n", false, false},
		{"raw string after package", clientGo, "package client\nvar marker = `\n// Code generated by clientgen. DO NOT EDIT.\n`\n", false, false},
		{"inside block comment", clientGo, "/*\n// Code generated by clientgen. DO NOT EDIT.\n*/\npackage client\n", false, false},
		{"different language", "client.txt", "// Code generated by clientgen. DO NOT EDIT.\n", false, false},
		{"generic warning", clientGo, "// DO NOT EDIT\npackage client\n", false, false},
		{"truncated line", clientGo, "// Code generated by clientgen. DO NOT EDIT.", false, false},
		{"past lines", clientGo, strings.Repeat("\n", roles.MaxHeaderLines) + "// Code generated by clientgen. DO NOT EDIT.\n", false, true},
		{"past bytes", clientGo, strings.Repeat("x", roles.MaxHeaderBytes) + "\n// Code generated by clientgen. DO NOT EDIT.\n", false, true},
	} {
		t.Run(tc.name, func(t *testing.T) {
			got, err := roles.ClassifyBlob(tc.path, []byte(tc.text))
			if err != nil {
				t.Fatal(err)
			}
			if got.Has(roles.Generated) != tc.generated || got.HeaderLimited != tc.limited {
				t.Fatalf("%+v", got)
			}
			if got.BytesExamined > roles.MaxHeaderBytes {
				t.Fatal("read limit")
			}
		})
	}
}

func FuzzBlob(f *testing.F) {
	f.Add([]byte("// Code generated by test. DO NOT EDIT.\n"))
	f.Fuzz(func(t *testing.T, data []byte) {
		got, err := roles.ClassifyBlob("vendor/client.go", data)
		if err != nil || !got.Has(roles.Vendor) || got.BytesExamined > min(len(data), roles.MaxHeaderBytes) {
			t.Fatal(got, err)
		}
	})
}
