package roles_test

import (
	"bytes"
	"errors"
	"io"
	"reflect"
	"strings"
	"testing"
	"testing/iotest"

	"github.com/git-pkgs/roles"
)

const clientGo = "client.go"

func TestBlob(t *testing.T) {
	for _, tc := range []struct {
		name, path, text   string
		generated, limited bool
	}{
		{"go marker", "src/client.go", "// Code generated by clientgen. DO NOT EDIT.\npackage client\n", true, false},
		{"crlf", clientGo, "// Code generated by clientgen. DO NOT EDIT.\r\npackage client\r\n", true, false},
		{"quoted", "client_test.go", "package client\nvar marker = \"// Code generated by clientgen. DO NOT EDIT.\"\n", false, false},
		{"raw string after package", clientGo, "package client\nvar marker = `\n// Code generated by clientgen. DO NOT EDIT.\n`\n", false, false},
		{"inside block comment", clientGo, "/*\n// Code generated by clientgen. DO NOT EDIT.\n*/\npackage client\n", false, false},
		{"different language", "client.txt", "// Code generated by clientgen. DO NOT EDIT.\n", false, false},
		{"generic warning", clientGo, "// DO NOT EDIT\npackage client\n", false, false},
		{"truncated line", clientGo, "// Code generated by clientgen. DO NOT EDIT.", false, false},
		{"past lines", clientGo, strings.Repeat("\n", roles.MaxHeaderLines) + "// Code generated by clientgen. DO NOT EDIT.\n", false, true},
		{"past bytes", clientGo, strings.Repeat("x", roles.MaxHeaderBytes) + "\n// Code generated by clientgen. DO NOT EDIT.\n", false, true},
	} {
		t.Run(tc.name, func(t *testing.T) {
			got, err := roles.ClassifyBlob(tc.path, []byte(tc.text))
			if err != nil {
				t.Fatal(err)
			}
			if got.Has(roles.Generated) != tc.generated || got.HeaderLimited != tc.limited {
				t.Fatalf("%+v", got)
			}
			if got.BytesExamined > roles.MaxHeaderBytes {
				t.Fatal("read limit")
			}
			fromReader, err := roles.ClassifyReader(tc.path, strings.NewReader(tc.text))
			if err != nil || !reflect.DeepEqual(fromReader, got) {
				t.Fatalf("ClassifyReader = %+v, want %+v, error %v", fromReader, got, err)
			}
		})
	}
}

func TestClassifyReaderBoundsAndErrors(t *testing.T) {
	reader := &countingReader{Reader: bytes.NewReader(bytes.Repeat([]byte("x"), roles.MaxHeaderBytes*2))}
	got, err := roles.ClassifyReader(clientGo, reader)
	if err != nil || !got.HeaderLimited || got.BytesExamined != roles.MaxHeaderBytes {
		t.Fatalf("bounded result = %+v, %v", got, err)
	}
	if reader.read != roles.MaxHeaderBytes+1 {
		t.Fatalf("bytes read = %d", reader.read)
	}
	failure := errors.New("read failed")
	if _, err := roles.ClassifyReader(clientGo, iotest.ErrReader(failure)); !errors.Is(err, failure) {
		t.Fatalf("reader error = %v", err)
	}
	if _, err := roles.ClassifyReader(clientGo, nil); err == nil {
		t.Fatal("accepted nil reader")
	}
	if _, err := roles.ClassifyReader("client.txt", iotest.ErrReader(failure)); err != nil {
		t.Fatalf("read non-Go content: %v", err)
	}
	if roles.ContentVersion == "" {
		t.Fatal("empty content version")
	}
}

func TestClassifierClassifyReader(t *testing.T) {
	classifier, err := roles.New([]roles.VendorRoot{{Path: cratesVendorRoot, EvidencePath: cargoConfig}})
	if err != nil {
		t.Fatal(err)
	}
	got, err := classifier.ClassifyReader("deps/crates/client.go", strings.NewReader("// Code generated by tool. DO NOT EDIT.\npackage client\n"))
	if err != nil || !got.Has(roles.Vendor) || !got.Has(roles.Generated) {
		t.Fatalf("ClassifyReader = %+v, %v", got, err)
	}
}

type countingReader struct {
	io.Reader
	read int
}

func (r *countingReader) Read(buffer []byte) (int, error) {
	count, err := r.Reader.Read(buffer)
	r.read += count
	return count, err
}

func FuzzBlob(f *testing.F) {
	f.Add([]byte("// Code generated by test. DO NOT EDIT.\n"))
	f.Fuzz(func(t *testing.T, data []byte) {
		got, err := roles.ClassifyBlob("vendor/client.go", data)
		if err != nil || !got.Has(roles.Vendor) || got.BytesExamined > min(len(data), roles.MaxHeaderBytes) {
			t.Fatal(got, err)
		}
		fromReader, err := roles.ClassifyReader("vendor/client.go", bytes.NewReader(data))
		if err != nil || !reflect.DeepEqual(fromReader, got) {
			t.Fatalf("reader differs: %+v, %v", fromReader, err)
		}
	})
}
