package roles_test

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"strings"
	"testing"

	"github.com/git-pkgs/roles"
)

func TestContentVersionFingerprint(t *testing.T) {
	cases := []struct {
		path, contents string
	}{
		{clientGo, "// Code generated by tool. DO NOT EDIT.\npackage client\n"},
		{clientGo, "// Code generated by tool. DO NOT EDIT.\r\npackage client\r\n"},
		{clientGo, "package client\nvar marker = \"// Code generated by tool. DO NOT EDIT.\"\n"},
		{clientGo, "/* // Code generated by tool. DO NOT EDIT. */\npackage client\n"},
		{clientGo, "// Code generated by tool. DO NOT EDIT."},
		{clientGo, strings.Repeat("\n", roles.MaxHeaderLines) + "// Code generated by tool. DO NOT EDIT.\n"},
		{clientGo, strings.Repeat("x", roles.MaxHeaderBytes) + "\n// Code generated by tool. DO NOT EDIT.\n"},
		{"client.txt", "// Code generated by tool. DO NOT EDIT.\n"},
		{clientPython, "# DO NOT EDIT\nprint(1)\n"},
		{appJS, "/* @generated */\nexport const version = 1;\n"},
		{appJS, "console.log(1);\n" + mapDirective},
		{appCSS, strings.Repeat(".foo{color:red}", 100)},
		{appJS, "const data = '" + strings.Repeat("a();", 300) + "';"},
		{appJS, strings.Repeat("a();", roles.MaxHeaderBytes)},
		{appJS, strings.Repeat("a", roles.MaxHeaderBytes-2) + "€\nb();\n"},
	}
	hash := sha256.New()
	for _, tc := range cases {
		result, err := roles.ClassifyBlob(tc.path, []byte(tc.contents))
		if err != nil {
			t.Fatal(err)
		}
		_, _ = fmt.Fprintf(hash, "%s\n", tc.path)
		if err := json.NewEncoder(hash).Encode(result); err != nil {
			t.Fatal(err)
		}
	}
	got := hex.EncodeToString(hash.Sum(nil))
	want, ok := map[string]string{
		"1": "e5085bec1fa3969071c52a75f04c064dd1af9ca18f034603b29cd14d869508d0",
		"2": "8897d21dc9c850d31ba3dab64542c0c05bb423bfcd0253e8e6df39786005aff3",
	}[roles.ContentVersion]
	if !ok || got != want {
		t.Fatalf("content semantics changed without a ContentVersion bump: version=%q fingerprint=%s", roles.ContentVersion, got)
	}
}
