package roles_test

import (
	"bytes"
	"reflect"
	"slices"
	"strings"
	"testing"

	"github.com/git-pkgs/roles"
)

const (
	clientPython = "client.py"
	appJS        = "src/app.js"
	appCSS       = "src/app.css"
	mapDirective = "//# sourceMappingURL=app.js.map\n"
)

func TestGeneratedSourceHeaders(t *testing.T) {
	for _, tc := range []struct {
		name, path, content string
		generated           bool
	}{
		{"python", clientPython, "# -*- coding: utf-8 -*-\n# Generated by protoc. DO NOT EDIT!\nfrom google.protobuf import descriptor\n", true},
		{"ruby", "client.rb", "#!/usr/bin/env ruby\n# Code generated by schema compiler\nrequire 'json'\n", true},
		{"shell", "client.sh", "#!/bin/sh\n# DO NOT EDIT\necho hello\n", true},
		{"java", "Client.java", "/*\n * @generated\n */\npackage client;\n", true},
		{"javascript", appJS, "/** @generated */\nexport const version = 1;\n", true},
		{"typescript", "client.ts", "// Code generated by schema compiler\nexport interface Client {}\n", true},
		{"css", appCSS, "/* DO NOT EDIT */\nbody { color: red; }\n", true},
		{"bom and crlf", "client.cs", "\ufeff// Code generated by tool\r\nclass Client {}\r\n", true},
		{"comment at eof", clientPython, "# DO NOT EDIT", true},
		{"lowercase", "client.rs", "// do not edit\nstruct Client;\n", true},
		{"string", clientPython, "marker = '# DO NOT EDIT'\n", false},
		{"docstring", clientPython, "\"\"\"\n# DO NOT EDIT\n\"\"\"\n", false},
		{"after code", appJS, "const example = 1;\n// DO NOT EDIT\n", false},
		{"unsupported", "README.md", "// Code generated by tool\n", false},
		{"directory path", "client.py/", "# DO NOT EDIT\n", false},
		{"binary", appJS, "// DO NOT EDIT\n\x00", false},
		{"invalid utf8", appJS, "// DO NOT EDIT\n\xff", false},
		{"partial tag", appJS, "// @generatedValue\n", false},
		{"incomplete block", appJS, "/* DO NOT EDIT", false},
		{"last allowed line", clientPython, strings.Repeat("\n", roles.MaxHeaderLines-1) + "# DO NOT EDIT\nprint(1)\n", true},
		{"past lines", clientPython, strings.Repeat("\n", roles.MaxHeaderLines) + "# DO NOT EDIT\n", false},
		{"past bytes", clientPython, strings.Repeat(" ", roles.MaxHeaderBytes) + "# DO NOT EDIT\n", false},
		{"rune split at limit", clientPython, "# DO NOT EDIT\n#" + strings.Repeat("x", roles.MaxHeaderBytes-16) + "é\nprint(1)\n", true},
		{"truncated comment", clientPython, "# DO NOT EDIT" + strings.Repeat(" ", roles.MaxHeaderBytes), false},
	} {
		t.Run(tc.name, func(t *testing.T) {
			got := classifyContent(t, tc.path, tc.content)
			if got.Has(roles.Generated) != tc.generated || got.Has(roles.Minified) {
				t.Fatalf("unexpected roles: %+v", got)
			}
		})
	}
}

func TestWebContent(t *testing.T) {
	compact := strings.Repeat("function f(a){return a+1;}", 100)
	for _, tc := range []struct {
		name, path, content string
		minified, sourceMap bool
	}{
		{"javascript", appJS, compact, true, false},
		{"module", "app.mjs", compact, true, false},
		{"commonjs", "app.cjs", compact, true, false},
		{"css", appCSS, strings.Repeat(".foo{color:red}", 100), true, false},
		{"under threshold", appJS, strings.Repeat("a();", 249), false, false},
		{"at threshold", appJS, strings.Repeat("a();", 250), true, false},
		{"pretty printed", appJS, strings.Repeat("function f(a) {\n  return a + 1;\n}\n", 100), false, false},
		{"whitespace", appJS, strings.Repeat("a();    ", 300), false, false},
		{"trailing whitespace", appJS, strings.Repeat("a();", 250) + strings.Repeat(" ", 100), false, false},
		{"long string", appJS, "const data = '" + compact + "';", false, false},
		{"long comment", appJS, "/*" + compact + "*/", false, false},
		{"line comment", appJS, "//" + compact, false, false},
		{"unsupported", "data.json", compact, false, false},
		{"large bundle", appJS, strings.Repeat(compact, 1000), true, false},
		{"js source map", appJS, "console.log(1);\n" + mapDirective, false, true},
		{"css source map", appCSS, "body{color:red}\n/*# sourceMappingURL=app.css.map */", false, true},
		{"legacy source map", appJS, "//@ sourceMappingURL=app.js.map", false, true},
		{"inline source map", appJS, "//# sourceMappingURL=data:application/json;base64,e30=\n", false, true},
		{"minified with map", appJS, compact + "\n" + mapDirective, true, true},
		{"empty map", appJS, "//# sourceMappingURL=\n", false, false},
		{"map prose", appJS, "// see sourceMappingURL=app.js.map\n", false, false},
		{"quoted map", appJS, "const text = '//# sourceMappingURL=app.js.map';", false, false},
		{"template map", appJS, "const text = `\n" + mapDirective + "`;", false, false},
		{"escaped template", appJS, "const text = `\\`\n" + mapDirective + "`;", false, false},
		{"map outside limit", appJS, strings.Repeat("\n", roles.MaxHeaderLines) + mapDirective, false, false},
		{"truncated map", appJS, "//# sourceMappingURL=" + strings.Repeat("x", roles.MaxHeaderBytes), false, false},
		{"rune split at limit", appJS, strings.Repeat("a", roles.MaxHeaderBytes-2) + "€\nb();\n", true, false},
	} {
		t.Run(tc.name, func(t *testing.T) {
			got := classifyContent(t, tc.path, tc.content)
			if got.Has(roles.Minified) != tc.minified || got.Has(roles.Generated) != (tc.minified || tc.sourceMap) {
				t.Fatalf("unexpected roles: %+v", got)
			}
			hasMap := slices.ContainsFunc(got.Evidence, func(e roles.Evidence) bool { return e.Rule == "generated.source-map" })
			if hasMap != tc.sourceMap {
				t.Fatalf("source map evidence: %+v", got.Evidence)
			}
		})
	}
}

func classifyContent(t *testing.T, name, content string) roles.BlobResult {
	t.Helper()
	got, err := roles.ClassifyBlob(name, []byte(content))
	if err != nil {
		t.Fatal(err)
	}
	reader := &countingReader{Reader: strings.NewReader(content)}
	fromReader, err := roles.ClassifyReader(name, reader)
	if err != nil || !reflect.DeepEqual(got, fromReader) {
		t.Fatalf("blob=%+v reader=%+v error=%v", got, fromReader, err)
	}
	if reader.read > roles.MaxHeaderBytes+1 || got.BytesExamined > roles.MaxHeaderBytes {
		t.Fatal("content read exceeded limit")
	}
	if got.HeaderChecked && got.HeaderLimited != (got.BytesExamined < len(content)) {
		t.Fatalf("incorrect inspection bounds: %+v", got)
	}
	return got
}

func TestContentVendorContext(t *testing.T) {
	classifier, err := roles.New([]roles.VendorRoot{{Path: "deps"}})
	if err != nil {
		t.Fatal(err)
	}
	name := "deps/src/app.min.js"
	content := []byte("// @generated\n" + strings.Repeat("a();", 300) + "\n" + mapDirective)
	got, err := classifier.ClassifyReader(name, bytes.NewReader(content))
	if err != nil {
		t.Fatal(err)
	}
	want := []roles.Role{roles.Source, roles.Vendor, roles.Generated, roles.Minified}
	if !slices.Equal(got.Roles, want) {
		t.Fatalf("roles = %v, want %v", got.Roles, want)
	}
	fromBlob, err := classifier.ClassifyBlob(name, content)
	if err != nil || !reflect.DeepEqual(got, fromBlob) {
		t.Fatalf("blob=%+v reader=%+v error=%v", fromBlob, got, err)
	}
}
