package roles

import (
	"bytes"
	"path"
	"regexp"
	"strings"
	"unicode/utf8"
)

const (
	minifiedLineBytes = 1000
	cssContent        = "css"
)

var generatedMarker = regexp.MustCompile(`(?i)\bcode generated by\b|\bdo not edit\b|(?:^|\s)@generated(?:\s|$)`)

func contentType(name string) string {
	switch path.Ext(name) {
	case ".go":
		return "go"
	case ".py", ".rb", ".sh":
		return "hash"
	case ".js", ".mjs", ".cjs", ".jsx", ".ts", ".tsx":
		return "javascript"
	case ".css":
		return cssContent
	case ".c", ".h", ".cc", ".cpp", ".hpp", ".cs", ".java", ".rs", ".swift", ".kt", ".dart":
		return "c"
	default:
		return ""
	}
}

func inspectSourceHeader(blob BlobResult, name string, header []byte) BlobResult {
	if blob.HeaderLimited {
		header = trimPartialRune(header)
	}
	if bytes.IndexByte(header, 0) >= 0 || !utf8.Valid(header) {
		return blob
	}
	kind := contentType(name)
	if generatedHeader(header, kind, blob.HeaderLimited) {
		blob.addContentEvidence(name, "generated.header", Generated, "header")
	}
	if kind == "javascript" || kind == cssContent {
		minified, sourceMap := inspectWebContent(header, kind, blob.HeaderLimited)
		if sourceMap {
			blob.addContentEvidence(name, "generated.source-map", Generated, "source-map")
		}
		if minified {
			blob.addContentEvidence(name, "generated.minified-content", Generated, "minified")
			blob.addContentEvidence(name, "minified.content", Minified, "long-line")
		}
	}
	return blob
}

func (b *BlobResult) addContentEvidence(name, rule string, role Role, subtype string) {
	b.Roles = (setOf(b.Roles) | roleBit(role)).List()
	b.Evidence = append(b.Evidence, Evidence{Rule: rule, Role: role, Path: name, Subtype: subtype, Source: "roles"})
}

func generatedHeader(header []byte, kind string, limited bool) bool {
	text := strings.TrimPrefix(string(header), "\ufeff")
	if strings.HasPrefix(text, "#!") {
		_, text, _ = strings.Cut(text, "\n")
	}
	for {
		text = strings.TrimLeft(text, " \t\r\n\v\f")
		comment, rest, ok := leadingComment(text, kind, limited)
		if !ok {
			return false
		}
		if generatedMarker.MatchString(comment) {
			return true
		}
		text = rest
	}
}

func leadingComment(text, kind string, limited bool) (comment, rest string, ok bool) {
	switch {
	case kind == "hash":
		if !strings.HasPrefix(text, "#") {
			return "", "", false
		}
		text = text[1:]
	case strings.HasPrefix(text, "/*"):
		comment, rest, ok = strings.Cut(text[2:], "*/")
		return comment, rest, ok
	case kind != cssContent && strings.HasPrefix(text, "//"):
		text = text[2:]
	default:
		return "", "", false
	}
	comment, rest, ok = strings.Cut(text, "\n")
	return comment, rest, ok || !limited
}

func inspectWebContent(header []byte, kind string, limited bool) (minified, sourceMap bool) {
	text := string(header)
	code, spaces := 0, 0
	finishLine := func() {
		minified = minified || minifiedLine(code, spaces)
		code, spaces = 0, 0
	}
	for len(text) > 0 {
		comment, rest, ok := leadingComment(text, kind, limited)
		if ok {
			sourceMap = sourceMap || sourceMapComment(comment)
			if strings.Contains(text[:len(text)-len(rest)], "\n") {
				finishLine()
			}
			text = rest
			continue
		}
		if strings.HasPrefix(text, "/*") || (kind != cssContent && strings.HasPrefix(text, "//")) {
			break
		}
		if text[0] == '\'' || text[0] == '"' || text[0] == '`' {
			end := quotedEnd(text)
			if strings.Contains(text[:end], "\n") {
				finishLine()
			}
			text = text[end:]
			continue
		}
		switch text[0] {
		case '\n', '\r':
			finishLine()
		case ' ', '\t':
			spaces++
		default:
			code++
		}
		text = text[1:]
	}
	finishLine()
	return minified, sourceMap
}

func minifiedLine(code, spaces int) bool {
	const whitespaceRatio = 10
	return code >= minifiedLineBytes && spaces*whitespaceRatio < code
}

func quotedEnd(text string) int {
	quote := text[0]
	for i := 1; i < len(text); i++ {
		switch text[i] {
		case '\\':
			i++
		case quote:
			return i + 1
		}
	}
	return len(text)
}

// trimPartialRune drops a multibyte rune split by the header byte limit so
// truncation does not disqualify an otherwise valid UTF-8 header.
func trimPartialRune(header []byte) []byte {
	for i := 1; i < utf8.UTFMax && i <= len(header); i++ {
		if !utf8.RuneStart(header[len(header)-i]) {
			continue
		}
		if !utf8.Valid(header[len(header)-i:]) {
			return header[:len(header)-i]
		}
		break
	}
	return header
}

func sourceMapComment(comment string) bool {
	if len(comment) == 0 || (comment[0] != '#' && comment[0] != '@') {
		return false
	}
	value, ok := strings.CutPrefix(strings.TrimSpace(comment[1:]), "sourceMappingURL=")
	return ok && len(strings.Fields(value)) == 1
}
