package roles_test

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"testing"

	"github.com/git-pkgs/roles"
)

type fingerprintRule struct {
	ID         string     `json:"id"`
	Kind       string     `json:"kind"`
	Pattern    string     `json:"pattern"`
	Role       roles.Role `json:"role"`
	Subtype    string     `json:"subtype,omitempty"`
	Ecosystem  string     `json:"ecosystem,omitempty"`
	Source     string     `json:"source"`
	Extensions []string   `json:"extensions,omitempty"`
}

const (
	fingerprintCargo      = "cargo"
	fingerprintNoticePath = "vendor/LICENSES/NOTICE"
	fingerprintVendorRoot = "deps/crates"
)

func TestCorpusVersionFingerprint(t *testing.T) {
	data, err := os.ReadFile("corpus/rules.json")
	if err != nil {
		t.Fatal(err)
	}
	var corpusData any
	if err := json.Unmarshal(data, &corpusData); err != nil {
		t.Fatal(err)
	}
	canonical, err := json.Marshal(corpusData)
	if err != nil {
		t.Fatal(err)
	}
	var corpus []fingerprintRule
	if err := json.Unmarshal(data, &corpus); err != nil {
		t.Fatal(err)
	}
	hash := sha256.New()
	_, _ = hash.Write(canonical)
	for _, rule := range corpus {
		path := rule.Pattern
		if strings.HasSuffix(rule.Kind, "-fold") {
			path = alternateCase(path)
		}
		switch rule.Kind {
		case "directory", "directory-fold", "directory-path":
			path += "/arbitrary.bin"
		case "suffix", "suffix-fold":
			path = "file" + path
		case "stem-fold":
			path += rule.Extensions[0]
		}
		result, err := roles.Classify(path)
		if err != nil {
			t.Fatal(err)
		}
		_, _ = fmt.Fprintf(hash, "\n%s\n", path)
		if err := json.NewEncoder(hash).Encode(result); err != nil {
			t.Fatal(err)
		}
	}

	for _, path := range []string{
		fingerprintNoticePath,
		"packages/parser/vendor/src/parser_test.go",
		"modules/a/testdata/package-lock.json",
		"packages/api/.github/workflows/ci.yml",
		"src/Form.Designer.cs",
		"main.go",
	} {
		result, err := roles.Classify(path)
		if err != nil {
			t.Fatal(err)
		}
		_, _ = fmt.Fprintf(hash, "\n%s\n", path)
		if err := json.NewEncoder(hash).Encode(result); err != nil {
			t.Fatal(err)
		}
	}

	classifier, err := roles.New([]roles.VendorRoot{{Path: fingerprintVendorRoot, Ecosystem: fingerprintCargo, EvidencePath: ".cargo/config.toml"}})
	if err != nil {
		t.Fatal(err)
	}
	contextResult, err := classifier.Classify("deps/crates/example/src/lib.rs")
	if err != nil {
		t.Fatal(err)
	}
	if err := json.NewEncoder(hash).Encode(contextResult); err != nil {
		t.Fatal(err)
	}
	blob, err := roles.ClassifyBlob("src/client.go", []byte("// Code generated by clientgen. DO NOT EDIT.\npackage client\n"))
	if err != nil {
		t.Fatal(err)
	}
	if err := json.NewEncoder(hash).Encode(blob); err != nil {
		t.Fatal(err)
	}

	got := hex.EncodeToString(hash.Sum(nil))
	want, ok := map[string]string{
		"1": "3d5ee1d9281183f54b6c440d484920f1fdef90f305a01b649be7f2a961739019",
	}[roles.CorpusVersion]
	if !ok || got != want {
		t.Fatalf("classification semantics changed without a CorpusVersion bump: version=%q fingerprint=%s", roles.CorpusVersion, got)
	}
}

func alternateCase(value string) string {
	lower := strings.ToLower(value)
	if value == lower {
		return strings.ToUpper(value)
	}
	return lower
}
