package roles_test

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"reflect"
	"strings"
	"testing"

	"github.com/git-pkgs/roles"
)

func TestClassifyPrefix(t *testing.T) {
	for _, tc := range []struct {
		name, path, prefix string
		generated          bool
		completeGenerated  bool
	}{
		{"empty", clientPython, "", false, false},
		{"partial hash comment", clientPython, "# DO NOT EDIT", false, true},
		{"complete hash comment", clientPython, "# DO NOT EDIT\n", true, true},
		{"partial line comment", appJS, "// @generated", false, true},
		{"complete line comment", appJS, "// @generated\n", true, true},
		{"partial block comment", appCSS, "/* DO NOT EDIT", false, false},
		{"complete block comment", appCSS, "/* DO NOT EDIT */", true, true},
		{"partial go comment", clientGo, "// Code generated by tool. DO NOT EDIT.", false, false},
		{"complete go comment", clientGo, "// Code generated by tool. DO NOT EDIT.\n", true, true},
		{"partial source map", appJS, "//# sourceMappingURL=app.js.map", false, true},
		{"complete source map", appJS, mapDirective, true, true},
		{"block source map", appCSS, "/*# sourceMappingURL=app.css.map */", true, true},
		{"split rune", clientPython, "# DO NOT EDIT\n# caf\xc3", true, false},
		{"invalid utf8", clientPython, "# DO NOT EDIT\n\xff\n", false, false},
		{"binary", clientPython, "# DO NOT EDIT\n\x00", false, false},
		{"marker after code", appJS, "const x = 1;\n// @generated\n", false, false},
	} {
		t.Run(tc.name, func(t *testing.T) {
			input := []byte(tc.prefix)
			before := bytes.Clone(input)
			got, err := roles.ClassifyPrefix(tc.path, input)
			if err != nil || !got.HeaderChecked || !got.HeaderLimited || got.BytesExamined != len(input) || got.Has(roles.Generated) != tc.generated {
				t.Fatalf("ClassifyPrefix = %+v, %v", got, err)
			}
			complete, err := roles.ClassifyBlob(tc.path, input)
			if err != nil || complete.HeaderLimited || complete.Has(roles.Generated) != tc.completeGenerated {
				t.Fatalf("ClassifyBlob = %+v, %v", complete, err)
			}
			if !bytes.Equal(input, before) {
				t.Fatal("input changed")
			}
		})
	}
}

func TestClassifyCachedPrefix(t *testing.T) {
	const window = 1024
	for _, tc := range []struct {
		name, content string
		generated     bool
	}{
		{"unterminated marker comment", "// @generated" + strings.Repeat(" ", window), false},
		{"complete marker", "// @generated\n" + strings.Repeat("const x = 1;\n", window), true},
		{"minified", strings.Repeat("a();", window), true},
	} {
		t.Run(tc.name, func(t *testing.T) {
			cached := make([]byte, window)
			if _, err := io.ReadFull(strings.NewReader(tc.content), cached); err != nil {
				t.Fatal(err)
			}
			got, err := roles.ClassifyPrefix(appJS, cached)
			if err != nil || !got.HeaderLimited || got.Has(roles.Generated) != tc.generated || got.Has(roles.Minified) != (tc.name == "minified") {
				t.Fatalf("cached prefix = %+v, %v", got, err)
			}
		})
	}
}

func TestClassifyPrefixBoundsAndContext(t *testing.T) {
	classifier, err := roles.New([]roles.VendorRoot{{Path: "deps"}})
	if err != nil {
		t.Fatal(err)
	}
	for _, input := range []string{
		strings.Repeat(" ", roles.MaxHeaderBytes) + "// @generated\n",
		strings.Repeat("\n", roles.MaxHeaderLines) + "// @generated\n",
	} {
		got, err := classifier.ClassifyPrefix("deps/app.js", []byte(input))
		if err != nil || !got.Has(roles.Vendor) || got.Has(roles.Generated) || !got.HeaderLimited {
			t.Fatalf("ClassifyPrefix = %+v, %v", got, err)
		}
		complete, err := classifier.ClassifyBlob("deps/app.js", []byte(input))
		if err != nil || !reflect.DeepEqual(got, complete) {
			t.Fatalf("prefix=%+v complete=%+v error=%v", got, complete, err)
		}
	}
	for _, name := range []string{"deps/README.md", "deps/app.js/"} {
		got, err := classifier.ClassifyPrefix(name, []byte("// @generated\n"))
		if err != nil || !got.Has(roles.Vendor) || got.Has(roles.Generated) || got.HeaderChecked || got.HeaderLimited || got.BytesExamined != 0 {
			t.Fatalf("path-only result = %+v, %v", got, err)
		}
	}
	if _, err := roles.ClassifyPrefix("../app.js", nil); !errors.Is(err, roles.ErrInvalidPath) {
		t.Fatalf("invalid path error = %v", err)
	}
}

func ExampleClassifyPrefix() {
	prefix := []byte("# DO NOT EDIT")
	result, err := roles.ClassifyPrefix("client.py", prefix)
	if err != nil {
		panic(err)
	}
	fmt.Println(result.Has(roles.Generated), result.HeaderLimited)
	// Output: false true
}
